name: srp
description: Secure Remote Password for dart &amp; flutter
version: 1.0.0
homepage: https://github.com/vipycm/srp

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.3

dev_dependencies:
  test: ^1.14.2

